version: '3.3'
services:
  message-server:
    container_name: rabbitmq
    image: rabbitmq:3.11-management
    hostname: "rabbitmq"
    restart: always
#    environment:
#      RABBITMQ_DEFAULT_USER: user
#      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - "E:/java-workspace/rabitmqConsumer/rabitmqConsumer/test/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro"
      - "E:/java-workspace/rabitmqConsumer/rabitmqConsumer/test/definitions.json:/etc/rabbitmq/definitions.json:ro"
#      - E:/java-workspace/rabitmqConsumer/rabitmqConsumer/test/definitions.json:/etc/rabbitmq/definitions.json
#      - E:/java-workspace/rabitmqConsumer/rabitmqConsumer/test/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
#      - "E:/java-workspace/rabitmqConsumer/rabitmqConsumer/etc/:/etc/rabbitmq/"
#      - "E:/java-workspace/rabitmqConsumer/rabitmqConsumer/test/:/var/lib/rabbitmq"
      - "E:/java-workspace/rabitmqConsumer/lib/:/var/lib/rabbitmq/"
      - "E:/java-workspace/rabitmqConsumer/log/:/var/log/rabbitmq"
#      - E:/java-workspace/rabitmqConsumer/definitions.json:/opt/definitions.json:ro
#      - E:/java-workspace/rabitmqConsumer/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      #- "E:/java-workspace/rabitmqConsumer/rabitmqConsumer/test/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
      #- "E:/java-workspace/rabitmqConsumer/rabitmqConsumer/test/definitions.json:/etc/rabbitmq/definitions.json"
    networks:
      - spring-cloud-network
  product-server:
    container_name: rabitconsumer
    image: digipay/rabbit-consumer
    restart: always
    depends_on:
      - message-server
    ports:
      - 8081:8081
      - 5008:5008
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008
    networks:
      - spring-cloud-network
  producer-server:
    container_name: rabitproduc
    image: digipay/rabbit-producer
    restart: always
    depends_on:
      - message-server
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge